### ISSUE TITLE
Invalid solc compilation Invalid option to --combined-json: compact-format

### ISSUE THREAD

**Issue by wegory** [crytic/slither#976]
Hello! :)

May I know how can I resolve this error on MacOS?

```
Invalid solc compilation Invalid option to --combined-json: compact-format
```

**Comment by spilehchiha** [comment]
1. Have you tried isolating the environment you're running `slither` in and using `solc-select`?

2. What is the command / script you're running with what arguments? Could you please elaborate more?

**Comment by MukeshJaiswal01** [comment]
👋 hi 
i got same  result 


First i  have compiled the contract with  **solc**  source/Manager.sol  and  then directly use **slither**  source/Manager.sol

**Comment by spilehchiha** [comment]
Hello, there. 👋 
Have you tried installing `solc-select` in a Python virtual environment (e.g.[https://virtualenvwrapper.readthedocs.io/en/latest/](virtualenvwrapper)) and run `slither` on your .sol file in the same virtual environment?

**Comment by enderphan94** [comment]
I got the same issue when using solc version 0.8.10. I've used solc-select to switch the version to 0.8.10 and got this error. I've also tried with the lower one of 0.8.9 but got no error with this version. Hmmm!

**Comment by RagePit** [comment]
It appears compact-format was removed in solc 0.8.10

https://github.com/crytic/crytic-compile/blob/master/crytic_compile/platform/solc.py#L404

**Comment by 0xalpharush** [comment]
This was an issue with crytic-compile that was now fixed https://github.com/crytic/crytic-compile/pull/221. We are releasing updates soon, or you can clone the latest branch and build locally.

**Comment by ericnordelo** [comment]
In this pull request, the --combined-json arg wasn't removed, and the compiler is still failing for me with the latest versions nowadays (slither and cryptic-compiler).

**Comment by ericnordelo** [comment]
I was using the solcjs version, which hasn't all the capabilities. I installed form brew (from official solidity docs), and now is working.
